[package]
name = "marcopolo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
krabmaga = "0.4.1"
nalgebra = "0.32.3"
uom = "0.35.0"
uuid = { version = "1.6.1", features = ["v4"] }
