name: deploy
# Controls when the workflow will run
on:
  # Triggers the workflow when build workflow succeeds but only for the "main" branch
  workflow_run:
    workflows: [ "build-python" ]
    types: [ "completed" ]
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  deploy-docs:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: site
          path: site
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
