name: python
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v3
      - run: pip install poetry
      - run: poetry build
  docs:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v3
      - run: pip install poetry
      - run: poetry install --with dev,docs
      - name: Export notebooks as examples
        run: poetry run make ipynb2md
      - name: MkDocs build
        run: poetry run mkdocs build
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: site
